{% set name = "thrax" %}
{% set version = "1.3.2" %}

package: 
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.opengrm.org/twiki/pub/GRM/ThraxDownload/{{ name }}-{{ version }}.tar.gz
  sha256: 6911235a434681be18b03f173eb2b6e93241f98c559f50c748ba84122c69ba92
  
build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - openfst ==1.7.6
  run:
    - openfst ==1.7.6
    - python

test:
  commands:
    - thraxcompiler --helpshort || [[ $? == 1 ]]
    - thraxmakedep || [[ $? == 1 ]]
    - thraxrewrite-tester --helpshort || [[ $? == 1 ]]

about:
  home: http://thrax.opengrm.org
  license: Apache-2.0
  license_file: COPYING
  summary: Finite-state grammar compilation
  description: |
    A library for compiling grammars expressed as regular expressions and context-dependent rewrite rules into weighted finite-state transducers
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/ThraxQuickTour

extra:
  recipe-maintainers:
    - kylebgorman
