{% set name = "thrax" %}
{% set version = "1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.opengrm.org/twiki/pub/GRM/ThraxDownload/{{ name }}-{{ version }}.tar.gz
  sha256: f6d0f51a741b181d6a4df65fb01409990be703444949704181db41a2158d37ea

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - openfst ==1.8.2
  run:
    - openfst ==1.8.2
    - python

test:
  commands:
    - thraxcompiler --helpshort || [[ $? == 1 ]]
    - thraxmakedep || [[ $? == 1 ]]
    - thraxrewrite-tester --helpshort || [[ $? == 1 ]]

about:
  home: http://thrax.opengrm.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Finite-state grammar compilation
  description: |
    A library for compiling grammars expressed as regular expressions and context-dependent rewrite rules into weighted finite-state transducers
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/ThraxQuickTour

extra:
  recipe-maintainers:
    - kylebgorman
