{% set name = "thrax" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.opengrm.org/twiki/pub/GRM/ThraxDownload/{{ name }}-{{ version }}.tar.gz
  sha256: 823182c9bca7f866437c0d8db9fc4c90688766f4492239bfbd73be20687c622e

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - openfst ==1.8.0
  run:
    - openfst ==1.8.0
    - python

test:
  commands:
    - thraxcompiler --helpshort || [[ $? == 1 ]]
    - thraxmakedep || [[ $? == 1 ]]
    - thraxrewrite-tester --helpshort || [[ $? == 1 ]]

about:
  home: http://thrax.opengrm.org
  license: Apache-2.0
  license_file: COPYING
  summary: Finite-state grammar compilation
  description: |
    A library for compiling grammars expressed as regular expressions and context-dependent rewrite rules into weighted finite-state transducers
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/ThraxQuickTour

extra:
  recipe-maintainers:
    - kylebgorman
